baseURL = 'http://slides.erinsmith.codes/'
languageCode = 'en-us'
title = 'Presentation Slides | Erin Smith Codes'

theme = "reveal-hugo"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true